canvas:
  height: 400
  width: 400
  background:
    color: "#FFFFFF"

mode: STEP
objects:
  - name: producer
    icon:
      shape: rectangle
      height: 30
      width: 90
      color: "#BBBBFF"
    label:
      value: Producer
      offsetX: -35
      offsetY: 5
      font: '17px Arial'
      style: bold
      color: black
    position:
      x: 200
      y: 45
  - name: p0
    icon:
      shape: database
      height: 60
      width: 60
      color: "#99CC99"
    label:
      value: P0
      offsetX: -10
      offsetY: 5
      font: '17px Arial'
      style: bold
      color: black
    position:
      x: 150
      y: 300
  - name: p1
    icon:
      shape: database
      height: 60
      width: 60
      color: "#BBBBFF"
    label:
      value: P1
      offsetX: -10
      offsetY: 5
      font: '17px Arial'
      style: bold
      color: black
    position:
      x: 250
      y: 300
  - name: d1
    icon:
      shape: rectangle
      height: 20
      width: 20
      color: "#BBBBFF"
      outline:
        thickness: 0
    position:
      x: 200
      y: 45
      z: 999
  - name: d2
    icon:
      shape: rectangle
      height: 20
      width: 20
      color: "#99CC99"
      outline:
        thickness: 0
    position:
      x: 200
      y: 45
      z: 999

steps:
  - transitions:
      - name: d1
        position:
          x.start: 200
          y.start: 45
          x.end: 250
          y.end: 300
    # interval between this step and next is 200ms
    nextInterval: 200
  - transitions:
      - name: d2
        position:
          x.start: 200
          y.start: 45
          x.end: 150
          y.end: 300
    # the duration of this transition is shortened by half (objects move faster)
    durationMultiplier: 0.5
  - transitions:
      - name: d1
        position:
          x.start: 200
          y.start: 45
          x.end: 250
          y.end: 300

